# Generated by Django 2.2.13 on 2022-07-31 17:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('api_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('api_secret', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_token', models.IntegerField()),
                ('instrument_token', models.IntegerField()),
                ('trading_symbol', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('last_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('expiry', models.DateField(blank=True, max_length=255, null=True)),
                ('strike', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('tick_size', models.IntegerField()),
                ('lot_size', models.IntegerField()),
                ('instrument_type', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('trading_symbol', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_symbol', models.CharField(max_length=255)),
                ('exchange', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('volume', models.IntegerField()),
            ],
            options={
                'unique_together': {('trading_symbol', 'exchange')},
            },
        ),
    ]
