# Generated by Django 4.0.6 on 2022-07-31 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtrader', '0002_alter_historicaldata_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicaldata',
            unique_together=set(),
        ),
    ]
